# Manually change the wallpaper with the below command:
# hyprctl hyprpaper reload ,"~/amogus.png"

# Permanently set the wallpaper by setting below:
wallpaper {
    monitor = eDP-1
    path = /home/user/Pictures/Wallpapers/house_trees_lake_mountains.jpeg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/user/Pictures/Wallpapers/house_trees_lake_mountains.jpeg
    fit_mode = cover
}
